#!/bin/bash
source /etc/unraid-version

if [[ ! -f /tmp/RAM-DISK-Dockerlog/modified ]] && [[ -f /boot/config/plugins/RAM-DISK-Dockerlog/settings.cfg ]]; then

    if [[ -f /usr/local/emhttp/plugins/RAM-DISK-Dockerlog/script/$version ]]; then
        interval=$(cat /boot/config/plugins/RAM-DISK-Dockerlog/settings.cfg)
        source /usr/local/emhttp/plugins/RAM-DISK-Dockerlog/script/$version
        
    else
    
        logger -t RAM-DISK-Dockerlog "Warning, no modification for $version found"
        
    fi

fi
